CREATE DATABASE IF NOT EXISTS SOLTIC;
USE SOLTIC;

CREATE TABLE  IF NOT EXISTS PROFILE (
NAME VARCHAR(50) NOT NULL,
USERNAME VARCHAR(50) UNIQUE NOT NULL,
COUNTRY VARCHAR(30),
AGE INT,
EMAIL VARCHAR(70) UNIQUE NOT NULL,
MOB BIGINT UNIQUE NOT NULL ,
JOININGDATE DATE,
PRIMARY KEY(USERNAME),
CHECK (MOB BETWEEN 1000000000 AND 9999999999)
);

CREATE TABLE IF NOT EXISTS TRIPS(
	ID VARCHAR(50) UNIQUE NOT NULL,
    USERNAME VARCHAR(50),
	STARTDATE DATE, 
    STARTLOC VARCHAR(50),
    ENDDATE DATE, 
    ENDLOC VARCHAR(50),
    ROOMSCOUNT INT,
    COST INT , 
    TRAVELLERSCOUNT INT,
    PRIMARY KEY(ID),
    FOREIGN KEY (USERNAME) REFERENCES PROFILE(USERNAME)
);

