--  Contains the Database Schema for UserProfile , Trips and Trip Participants 
CREATE DATABASE IF NOT EXISTS SOLTIC;
USE SOLTIC;

CREATE TABLE  IF NOT EXISTS PROFILE (
NAME VARCHAR(50) NOT NULL,
USERNAME VARCHAR(50) UNIQUE NOT NULL,
COUNTRY VARCHAR(30),
AGE INT,
EMAIL VARCHAR(70) UNIQUE NOT NULL,
MOB BIGINT UNIQUE NOT NULL ,
JOININGDATE DATE,
PASSWORD VARCHAR(15) NOT NULL,
PROFESSION VARCHAR(20),
BIO VARCHAR(100),
PRIMARY KEY(USERNAME),
CHECK (MOB BETWEEN 1000000000 AND 9999999999)
);



CREATE TABLE IF NOT EXISTS TRIPS (
  ID VARCHAR(50) UNIQUE PRIMARY KEY,
  USERNAME VARCHAR(50) NOT NULL,

  STARTDATE DATE NOT NULL,
  ENDDATE DATE NOT NULL,
  STARTLOC VARCHAR(50) NOT NULL,
  ENDLOC VARCHAR(50) NOT NULL,

  MODE VARCHAR(20),              -- train, flight, road
  BUDGET INT,
  TRAVELLERSCOUNT INT,
  ROOMSCOUNT INT,
  COST INT,
  RATING INT,

  STATUS VARCHAR(20) DEFAULT 'scheduled', -- scheduled , active , completed , cancelled
  STARTED_AT DATETIME DEFAULT NULL,
  COMPLETED_AT DATETIME DEFAULT NULL,

  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (USERNAME) REFERENCES PROFILE(USERNAME)
);


-- Saved For Future Work when a Trip have multiple participants , No use for Now 
CREATE TABLE IF NOT EXISTS TRIP_PARTICIPANTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TRIP_ID VARCHAR(50) NOT NULL,
  USERNAME VARCHAR(50) NOT NULL,

  ROLE VARCHAR(20) DEFAULT 'MEMBER', -- OWNER | MEMBER
  JOINED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,

  FOREIGN KEY (TRIP_ID) REFERENCES TRIPS(ID),
  FOREIGN KEY (USERNAME) REFERENCES PROFILE(USERNAME),

  UNIQUE (TRIP_ID, USERNAME)
);
