CREATE DATABASE IF NOT EXISTS SOLTIC;
USE SOLTIC;

CREATE TABLE  IF NOT EXISTS PROFILE (
NAME VARCHAR(50) NOT NULL,
USERNAME VARCHAR(50) UNIQUE NOT NULL,
COUNTRY VARCHAR(30),
AGE INT,
EMAIL VARCHAR(50) UNIQUE NOT NULL,
MOB INT UNIQUE NOT NULL,
JOININGDATE DATE
);

CREATE TABLE IF NOT EXISTS TRIPS(
	STARTDATE DATE, 
    STARTLOC VARCHAR(50),
    ENDDATE DATE, 
    ENDLOC VARCHAR(50),
    ROOMSCOUNT INT,
    COST INT , 
    TRAVELLERSCOUNT INT
)